FROM alpine:latest AS builder

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY . /build/
WORKDIR /build/

RUN mkdir -p /app && cp -a . /app/

RUN chmod 555 /app/QuickNote

FROM scratch

COPY --from=builder /etc/passwd /etc/passwd

COPY --from=builder /etc/group /etc/group

COPY --from=builder --chown=appuser:appgroup /app /opt/quicknote

USER appuser
EXPOSE 3000

WORKDIR /opt/quicknote

CMD ["./QuickNote"]